spring:
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: "jdbc:postgresql://localhost:5432/springbootjpa"
    username: oktatutorial
    password: abcd1234
okta:
  oauth2:
    issuer: https://dev-533919.oktapreview.com/oauth2/default
    clientId: 0oahpnkb44pcaOIBG0h7
    scope: openid profile email
    rolesClaim: groups