# so as not to conflict with Vue on 8080
server:
  port: 9000

okta:
  oauth2:
    issuer: https://dev-533919.oktapreview.com/oauth2/default
    clientId: 0oaf3k743pAYOxLto0h7
    scope: openid profile email
      