okta:
  oauth2:
    issuer: https://dev-533919.oktapreview.com/oauth2/default
    client-id: 0oak8fz26cLefbPGC0h7
    client-secret: xfPqP8G2dal39dcHr13IceUV3H44Y-eui1ymME_j
spring:
  thymeleaf:
    cache: false