const ADD_ITEM_TO_CART = 'Add item to cart'
const REMOVE_ITEM_FROM_CART = 'Remove item from cart'
const SET_NAVBAR_TITLE = 'SET_NAVBAR_TITLE'
const SET_SHIPPING_DETAILS = 'SET_SHIPPING_DETAILS'
const SET_SINGLE_ORDER = 'SET_SINGLE_ORDER'
const SET_AUTH_DETAILS = 'SET_AUTH_DETAILS'
const SET_ONLY_LOGGED_IN_STATUS = 'SET_ONLY_LOGGED_IN_STATUS'
const SET_CURRENT_ACTIVITY = 'SET_CURRENT_ACTIVITY'
const RESET_CART = 'RESET_CART'
const CHANGE_NAME = 'CHANGE_NAME'
const CHANGE_EMAIL = 'CHANGE_EMAIL'
const RESET_AUTH_DETAILS = 'RESET_AUTH_DETAILS'

export {ADD_ITEM_TO_CART, REMOVE_ITEM_FROM_CART, SET_NAVBAR_TITLE,
        SET_SHIPPING_DETAILS,SET_SINGLE_ORDER, SET_AUTH_DETAILS,
        SET_ONLY_LOGGED_IN_STATUS,SET_CURRENT_ACTIVITY,RESET_CART,
        CHANGE_NAME,CHANGE_EMAIL,RESET_AUTH_DETAILS}