const CHECKING_OUT = 'CHECKING_OUT'
const CHANGING_NAME = 'CHANGING_NAME'
const CHANGING_EMAIL = 'CHANGING_EMAIL'
const VIEWING_PROFILE = 'VIEWING_PROFILE'
const SIGNING_OUT = 'SIGNING_OUT'
const VIEWING_ORDER_HISTORY = 'VIEWING_ORDER_HISTORY'
const VIEWING_SINGLE_ORDER = 'VIEWING_SINGLE_ORDER'

export { CHECKING_OUT,CHANGING_EMAIL,CHANGING_NAME,VIEWING_PROFILE,
       SIGNING_OUT,VIEWING_ORDER_HISTORY,VIEWING_SINGLE_ORDER}