version: '3'
services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=donuts
      - MYSQL_USER=splitdemo
      - MYSQL_PASSWORD=splitdemo
    ports:
      - 3306:3306
    volumes:
      - db-data:/var/lib/mysql
  app:
    build: ./
    restart: on-failure
    depends_on:
      - db
    ports:
      - 8080:8080
    environment:
      - DATABASE_HOST=db
      - DATABASE_USER=splitdemo
      - DATABASE_PASSWORD=splitdemo
      - DATABASE_NAME=donuts
      - DATABASE_PORT=3306
volumes:
  db-data: